export default {
  port: process.env.PORT || 5000,
  appName: 'rest-guide',
  databaseUrl: 'mongodb://mongo1:27018,mongo2:27019,mongo3:27020/test?replicaSet=rs0',
  jwtSecretKey: '123467890',
  apiDocsUsername: 'username',
  apiDocsPassword: 'password',
  mailService: 'sendgrid',
  mailServiceApiKey: process.env.MAIL_SERVICE_API_KEY,
  mailServiceSender: process.env.MAIL_SERVICE_SENDER,
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY,
  vapidPrivateKey: process.env.VAPID_PRIVATE_KEY,
  fileUploadService: 'minio',
  fileUploadServiceUrl: process.env.MINIO_URL,
  fileUploadServicePort: process.env.MINIO_PORT,
  fileUploadServiceAccessKey: process.env.MINIO_ACCESS_KEY,
  fileUploadServiceSecretKey: process.env.MINIO_SECRET_KEY,
  fileUploadServiceExternalUrl: process.env.MINIO_EXTERNAL_URL,
};
